active = false
[qq]
appId = "BotId"
appSecret = "BotSecret"
appToken = "BotToken"

[miyoushe]
creator = "creatorId"
botId = "BotId"
pubKey = """-----BEGIN PUBLIC KEY-----\nYour PubKey\n-----END PUBLIC KEY-----\n"""
secret = "Secret"